### PR TITLE
Removing item attributes functions

### PR DESCRIPTION
**Pull request by DontAskM8**
i dont have custom named/description items. So I cant test if those 2 works. Anything related to removecustomization simple should work. RequestInventoryRefresh is tested for working. User not require to get off the game and back in to reload steam inventory

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
I like the thought of bringing the "restore" function to the module, though I think rather than having a bunch of methods, it would be more useful to have one function that takes an enum or string parameter to specify which element to remove.

**Comment by DontAskM8** [comment]
Seems nice, ill try im pretty bad at making modules and such. Removing strange parts seems pretty complex, so i didnt include that for now. Closed the pull request for now because the `requestInventoryRefresh` is actually for TF2's local inventory. Still need to restart the game to update the inventories on steam side.

**Comment by DontAskM8** [comment]
@DoctorMcKay  went abit of searching but only found this for steam `k_EMsgEconFlushInventoryCache` idk what this does but from the name itself seems like to flush out old inventory ? and maybe get the updated one ?

**Comment by DoctorMcKay** [comment]
Just go ahead and give up on the thought of flushing the inventory cache with some tricky code. The only way it can be done is by launching/quitting the game in question, completing a trade offer containing an item from the game in question, or starting a real-time trading session.

If you *really* want to flush your bot's inventory cache without starting/quitting a game, you can [have your bot open a trading session with another bot](https://github.com/DoctorMcKay/node-steam-user#tradesteamid).

**Pull request closed without merging**
